
sudo: required

services:
    - docker

script:
    - docker build -t mjalas/composer .
    - docker run --name composer --rm mjalas/composer /bin/sh -c "echo Done!"    

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker tag $(docker images | grep mjalas/composer | awk {'print $3'}) mjalas/composer:latest
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker push mjalas/composer;
      fi